# Elsevier configuration

executor:
  publisher_name: elsevier
  res_type: metadata
  resource_dir: /data/core/dit/data/
  metadata_dir: resourcesync/elsevier/metadata
  url_prefix: http://core.ac.uk/omtd
  max_items_in_list: 50000
  zero_fill_filename: 4
  is_saving_pretty_xml: True
  is_saving_sitemaps: True
  has_wellknown_at_root: True
  description_dir: /data/core/dit/data/
  elastic_host: core-index01.open.ac.uk
  elastic_port: 9200
  elastic_index: resourcesync
  elastic_resource_type: resource