populator:
  publishers:
    - name: elsevier
      resources: /data/core/dit/data/elsevier/metadata/000
      subfolders: ['']
      type: metadata
    - name: elsevier
      resources: /data/core/dit/data/elsevier/pdf/000
      subfolders: ['']
      type: pdf
  elastic_host: core-index01.open.ac.uk
  elastic_port: 9200
  elastic_index: resourcesync
  elastic_resource_type: resource