# The Data Interoperability Toolkit ResourceSync simulator configuration

##### Source Configuration #####

source:
  server_name: Data Interoperability Toolkit
  gen_files: ['config/elsevier','config/springer']
  url_prefix: http://giorgios-macbook-pro.local:8888
  port: 8888
  resource_dir: /Users/giorgio/Desktop/dit/