# The Data Interoperability Toolkit ResourceSync simulator configuration

##### Source Configuration #####

source:
  server_name: Data Interoperability Toolkit
  resource_dir: /Users/giorgio/Desktop/dit/
  metadata_dir: metadata/springer
  url_prefix: http://giorgios-macbook-pro.local:8888
  port: 8888
  # select_mode: selector
  max_items_in_list: 25700
  zero_fill_filename: 4
  is_saving_pretty_xml: True
  is_saving_sitemaps: True
  has_wellknown_at_root: True
  description_dir: /Users/giorgio/Desktop/dit
  elastic_index: resourcesync-springer
  # selector_file: /Users/giorgio/Desktop/rspub-selectors/dit-selector.csv